.include "../Makefile.inc"
.include "${ABSTOP}/mk/cppprog.mk"
.include "${ABSTOP}/mk/libd.mk"

PROG=		echod
CPPFLAGS+=	-I${INCLUDEDIR}
CPPFLAGS+=	-ggdb3
SRCS+=		main.cpp echod.cpp

.include <bsd.prog.mk>
# vim: set ft=make ts=8 sw=8 noet:
