.include <bsd.own.mk>

.include "../Makefile.inc"
.include "${ABSTOP}/mk/cpp.mk"

CXXFLAGS+=	-std=c++0x
LDSTATIC=	-static
LIB= 		qt

.include "qt.mk"

FILES+= Qt
FILESDIR=	${INCLUDEDIR}/qt

.include <bsd.lib.mk>

# vim: set ts=8 sw=8 noet:
