#ifndef QCONFIG_PRIVATE_H
#define QCONFIG_PRIVATE_H
#define QT_NO_THREAD
#define QT_NO_QOBJECT
#define QT_NO_CODECS
#define QT_NO_UNICODETABLES
#define QT_NO_DATASTREAM
#define QT_NO_TRANSLATION
#define QT_BOOTSTRAPPED
#define QT_LITE_UNICODE
#define QT_NO_CAST_TO_ASCII
#define QT_NO_LIBRARY
#define QT_NO_SYSTEMLOCALE
#define QT_NO_TRANSLATION
#define QT_QMAKE_LOCATION
#define QT_NO_CAST_FROM_ASCII
#endif //! QCONFIG_PRIVATE_H
